services:
  git-watcher-bot:
    image: ghcr.io/maaad/git-watcher-bot:latest
    build: .
    restart: unless-stopped
    env_file:
      - .env
    working_dir: /data
    volumes:
      - git-watcher-data:/data
    command: ["git-watcher-bot"]

volumes:
  git-watcher-data:

